services:
  minecraft-server:
    build: .
    volumes:
      - './world:/server/world'
    ports:
      - "25565:25565"
      - "25575:25575"
    restart: unless-stopped
    stdin_open: true
    tty: true